pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io
import "root:/config"

// The wallpaper folder, the caches pibble generates beside it, and the
// client-side "xray" blur that stands in for compositor blur.
//
// Both halves live here together because they are produced by one scan: the
// blurred variant the launcher draws behind itself and the $BLUR a wallpaper
// command receives are the same file, generated by the same background pass
// that generates thumbnails.
Singleton {
    id: root

    // Injected by LauncherWindow, which is the only thing that knows which
    // output the launcher actually mapped onto. Until it exists (and if it
    // never does) the primary output stands in, so the very first scan is
    // still keyed on real geometry.
    property var screen: Quickshell.screens.length > 0 ? Quickshell.screens[0] : null
    // Also injected by LauncherWindow: a wallpaper applied while the launcher
    // is up must not swap the backdrop out from under it (see syncXrayShown).
    property bool launcherShown: false

    readonly property string dir: SystemInfo.expandHome(Settings.wallpaperDir)

    // Each entry: path|thumb|blurred|pan. All three generated variants point
    // into cacheRoot, keyed by a hash of the source path (stable across
    // renames of unrelated files, safe across multiple wallpaperDirs);
    // <stem>blurred.<ext> next to the source is still honored as a
    // user-supplied override of the blurred one.
    //
    // The cache is split by the *shape* of what it holds, not by which pane
    // reads it - one file often serves two - so a variant's directory says
    // what it is:
    //
    //   thumbnails/crops   480x270 center crop, images and gifs
    //   thumbnails/wide    uncropped, source aspect, <=1920x1080
    //   thumbnails/clips   the clipboard's own thumbs (Clipboard owns these)
    //   blurred            output-sized and pre-blurred, see the xray block
    //
    // thumb is what a grid tile draws and pan is what the carousel slides a
    // fixed window across, so an image's thumb is its crop and its pan is its
    // wide still. A video has no crop at all - Image can't decode the source
    // file - so its wide still is both, one file under one name.
    //
    // One blurred image serves both uses: the launcher's own backdrop in
    // "xray" mode and the $BLUR the wallpaper command gets (see
    // applyWallpaper) - they're the same picture, so they're the same file.
    property var list: []
    // raw stdout of the scan `list` was last built from; see where it's compared
    property string lastScanText: ""
    // xrayCacheKey as of the last scan that landed. Only when it matches the
    // current one do the entries say anything about the backdrops the
    // launcher is actually after - before that (a scan from before the
    // output scale resolved, say) a missing entry means "not looked for
    // yet", not "not there".
    property string scanKey: ""
    property string lastMissingDir: ""
    // matugen chokes on/slow-decodes an animated source (and can't read
    // video at all); sample the cached static thumbnail instead when the
    // current wallpaper is a .gif or .mp4 (see Theme's matugen run). Falls back to
    // the raw path before the background scan has generated a thumbnail for
    // it yet.
    readonly property string matugenSource: {
        const w = root.list.find(x => x.path === Settings.currentWallpaper);
        return (w && (w.gif || w.video) && w.thumb) ? w.thumb : Settings.currentWallpaper;
    }
    // Started a tick late: this is called from change handlers on the very
    // properties the scan's own command binding reads (see xrayCacheKey), and
    // a binding is only guaranteed to have caught up by the time the next one
    // reads it - flipping `running` inline reliably ran the scan against the
    // previous geometry.
    function rescan(): void {
        scan.running = false;
        Qt.callLater(() => scan.running = true);
    }
    // cache entries the last scan found missing, and the one re-scan armed
    // to pick them up once the background generation has written them (see
    // where it's armed, in scan's output handler)
    property string generationMissing: ""
    Timer {
        id: generationRetry
        interval: 3000
        onTriggered: root.rescan()
    }
    Process {
        id: scan
        running: true
        // the xray parameters this run went looking for, captured at spawn
        // rather than read back when it finishes - the two can differ by a
        // whole scan (the output scale resolving is exactly that case), and
        // reading it late would claim a stale result was current
        property string scanKey: ""
        onRunningChanged: if (running) scanKey = root.xrayCacheKey
        command: ["bash", "-c", `
            cd "$1" || { echo NODIR; exit 0; }
            cachedir="$2"
            shopt -s nullglob nocaseglob
            for f in *.png *.jpg *.jpeg *.webp *.gif *.mp4; do
                case "$f" in *blurred.*) continue ;; esac
                stem="\${f%.*}" ext="\${f##*.}"
                isvid=0; case "\${ext,,}" in mp4) isvid=1 ;; esac
                # a generated crop is true-color (png) even for a .gif source:
                # writing a single decoded frame back out as .gif would
                # quantize it to a 256-color palette, banding badly once
                # blurred. The source itself is still played back untouched.
                oext="$ext"; case "\${ext,,}" in gif) oext="png" ;; esac
                # versioned like bkey below (r<n>): bump t<n> (here and in
                # the generation pass) whenever the magick crop recipe
                # changes, so stale entries fall out of the sweep instead of
                # sticking around under the old recipe until their source file
                # happens to change.
                key=$(printf '%s' "$PWD/$f|t3" | md5sum | cut -d' ' -f1)
                # the wide still, versioned the same way (p<n>) and for the
                # same reason as the two keys around it
                pkey=$(printf '%s' "$PWD/$f|p1" | md5sum | cut -d' ' -f1)
                # the blurred variant is the one cache entry that depends on
                # more than the source file, so the output geometry, the blur
                # and the recipe version go in its key too: a resized output,
                # a retuned kernel or a changed recipe then lands on a
                # different name, and the old one falls out of the sweep
                # below like any other dead entry. Bump r<n> (here and in the
                # generation pass) whenever the magick command changes.
                bkey=$(printf '%s' "$PWD/$f|$3|$4|r5" | md5sum | cut -d' ' -f1)
                # the wide still is a jpeg when magick writes it and a png when
                # ffmpeg does - see the two calls in the generation pass
                wide="$cachedir/thumbnails/wide/$pkey.jpg"
                [ "$isvid" = "1" ] && wide="$cachedir/thumbnails/wide/$pkey.png"
                thumb="" blur="" pan=""
                # only trust caches newer than the source image
                [ "$wide" -nt "$f" ] && pan="$wide"
                if [ "$isvid" = "1" ]; then
                    # a video has no crop of its own: Image can't decode the
                    # source file at all, so the wide still is what the grid
                    # tile draws as well as what the carousel pans across.
                    # Both stay empty until the generation pass takes it.
                    thumb="$pan"
                else
                    # a fresh image/gif stands in as its own tile (the Image
                    # element decodes it directly, just slowly) until the crop
                    # lands
                    thumb="$PWD/$f"
                    [ "$cachedir/thumbnails/crops/$key.$oext" -nt "$f" ] && thumb="$cachedir/thumbnails/crops/$key.$oext"
                fi
                [ "$cachedir/blurred/$bkey.png" -nt "$f" ] && blur="$cachedir/blurred/$bkey.png"
                [ -e "\${stem}blurred.$ext" ] && blur="$PWD/\${stem}blurred.$ext"
                printf '%s|%s|%s|%s\\n' "$PWD/$f" "$thumb" "$blur" "$pan"
            done | sort`, "_", root.dir, SystemInfo.cacheRoot,
            root.xraySize.width + "x" + root.xraySize.height, String(root.xrayCacheSigma)]
        stdout: StdioCollector {
            onStreamFinished: {
                root.scanKey = scan.scanKey;
                if (text.trim() === "NODIR") {
                    root.lastScanText = text;
                    root.list = [];
                    if (root.lastMissingDir !== root.dir) {
                        root.lastMissingDir = root.dir;
                        Notifier.error("Wallpaper folder not found", root.dir + "\n\nChange it in Settings > Pages > Wallpapers path.");
                    }
                    return;
                }
                root.lastMissingDir = "";
                const walls = text.trim().split("\n").filter(l => l).map(l => {
                    const p = l.split("|");
                    return { path: p[0], thumb: p[1], blur: p[2] || "", pan: p[3] || "", gif: /\.gif$/i.test(p[0]), video: /\.mp4$/i.test(p[0]) };
                });
                // Reassigning this array invalidates every tile's model entry,
                // which tears each delegate down and rebuilds it - re-creating
                // its ClippingRectangle render target and re-uploading its
                // thumbnail texture. A scan runs on every launcher open, and
                // the folder is almost never different between two of them, so
                // that cost was being paid mid-reveal for an identical result.
                // The scan's raw output is the canonical form of everything
                // `walls` is derived from, so an unchanged one means an
                // unchanged model: keep the existing array and its delegates.
                if (text !== root.lastScanText) {
                    root.lastScanText = text;
                    root.list = walls;
                }
                // Generate missing thumbnails (a full 5K image standing in as
                // its own thumbnail costs ~100ms to decode+upload), pan
                // sources and blurred
                // variants in the background; the next scan picks them up and
                // applying never has to blur synchronously. Also sweeps cache
                // entries whose source wallpaper is gone - runs every scan
                // (not just when something's missing) so deletions get cleaned
                // up promptly.
                //
                // Both consumers of the blurred variant gate it the same way:
                // it's wanted if the launcher draws it (xray mode) or the
                // wallpaper command asks for it ($BLUR). The geometry check is
                // what holds it back until the output scale it's keyed on has
                // resolved.
                const wantBlur = (Settings.bgBlur === "xray" || Settings.wallCommand.includes("$BLUR"))
                    && root.xraySize.width > 0 && root.xrayCacheSigma > 0;
                // current wallpaper first: on a cold cache its backdrop is the
                // one thing the launcher needs before any other entry, and a
                // big folder is minutes of work to get through
                const paths = walls.map(w => w.path);
                const cur = paths.indexOf(Settings.currentWallpaper);
                const order = cur > 0 ? [paths[cur]].concat(paths.slice(0, cur), paths.slice(cur + 1)) : paths;
                // Arm one follow-up scan whenever anything is still missing:
                // the pass below is fire-and-forget, so nothing reports when
                // its output lands, and until a scan sees the files the
                // launcher keeps falling back (a sharp thumbnail-less video
                // tile, a live-blurred backdrop). Comparing against the last
                // set of missing entries is what keeps a cache that *can't*
                // be filled - no ImageMagick - from scanning on a loop: it
                // only re-arms while the set is still shrinking.
                const missing = walls.filter(w => w.thumb === "" || w.pan === "" || (wantBlur && w.blur === "")).map(w => w.path).join("|");
                if (missing !== "" && missing !== root.generationMissing)
                    generationRetry.restart();
                root.generationMissing = missing;
                Quickshell.execDetached(["bash", "-c", `
                    walldir="$1" cachedir="$2" gb="$3" alerts="$4" xgeom="$5" xsigma="$6"; shift 6
                    mkdir -p "$cachedir/thumbnails/crops" "$cachedir/thumbnails/wide" "$cachedir/blurred"
                    # Layouts this cache has had before: wallpapers/ + xray/
                    # (from when the backdrop had a cache of its own, before
                    # thumbnails/ and blurred/ moved up next to the
                    # clipboard's), then a flat thumbnails/ beside a pan/ -
                    # both since split by shape into the two directories
                    # above. Regenerating an entry is a second or so, so the
                    # old trees just go rather than being migrated. The find
                    # is what clears the flat layout without touching the
                    # subdirectories that replaced it.
                    rm -rf "$cachedir/wallpapers" "$cachedir/xray" "$cachedir/pan"
                    find "$cachedir/thumbnails" -maxdepth 1 -type f -delete 2>/dev/null
                    # one generation pass at a time: scans are cheap and fire
                    # on every open, and two passes racing on the same cache
                    # entry is duplicated magick work at best
                    exec 9>"$cachedir/.generating"
                    flock -n 9 || exit 0
                    warnedMagick=0
                    warnedFfmpeg=0
                    live=""
                    for f in "$@"; do
                        b=$(basename "$f")
                        stem="\${b%.*}" ext="\${b##*.}"
                        isvid=0; case "\${ext,,}" in mp4) isvid=1 ;; esac
                        # see the matching oext note in the scan pass above
                        oext="$ext"; case "\${ext,,}" in gif) oext="png" ;; esac
                        # see the matching key note in the scan pass above
                        key=$(printf '%s' "$f|t3" | md5sum | cut -d' ' -f1)
                        # see the matching pkey note in the scan pass above
                        pkey=$(printf '%s' "$f|p1" | md5sum | cut -d' ' -f1)
                        # see the matching bkey note in the scan pass above
                        bkey=$(printf '%s' "$f|$xgeom|$xsigma|r5" | md5sum | cut -d' ' -f1)
                        wide="$cachedir/thumbnails/wide/$pkey.jpg"
                        [ "$isvid" = "1" ] && wide="$cachedir/thumbnails/wide/$pkey.png"
                        live="$live $key $bkey $pkey"
                        needcrop=0 needblur=0 needwide=0
                        # a video has no crop entry - the wide still stands in
                        # for one everywhere (see the scan pass)
                        if [ "$isvid" = "0" ]; then
                            [ "$cachedir/thumbnails/crops/$key.$oext" -nt "$f" ] || needcrop=1
                        fi
                        [ "$wide" -nt "$f" ] || needwide=1
                        if [ "$gb" = "1" ]; then
                            [ "$cachedir/blurred/$bkey.png" -nt "$f" ] || [ -e "$walldir/\${stem}blurred.$ext" ] || needblur=1
                        fi
                        if [ "$needcrop" = "1" ] || [ "$needblur" = "1" ] || [ "$needwide" = "1" ]; then
                            if [ "$isvid" = "1" ]; then
                                if ! command -v ffmpeg >/dev/null 2>&1; then
                                    if [ "$warnedFfmpeg" = "0" ] && [ "$alerts" = "1" ]; then
                                        warnedFfmpeg=1
                                        notify-send -a pibble -i system-software-install "ffmpeg not found" "ffmpeg is used to generate video wallpaper thumbnails and blurred previews - install it for sharper, faster previews."
                                    fi
                                else
                                    # a video's only entry, and it goes in
                                    # wide/ rather than being cropped like the
                                    # images below: this frame is what the
                                    # picker paints while the live video isn't
                                    # playing, and PreserveAspectCrop derives
                                    # its scale from the source aspect, so a
                                    # 16:9 still standing in for a video that
                                    # isn't 16:9 lands at a different crop than
                                    # the video itself - a visible zoom the
                                    # instant playback starts. Keeping the
                                    # source aspect makes the two identical in
                                    # any box.
                                    #
                                    # Capped at 1920 wide rather than a small
                                    # fixed size: this still doesn't only back
                                    # the grid's 240x135 tile (which
                                    # downscales at decode time regardless of
                                    # source size) - the carousel decodes the
                                    # same file at up to ~barHeight tall and
                                    # pans across it. A 480px-wide still
                                    # stretched to fill that box read as
                                    # blurrier than the live video it hands
                                    # off to. min() so a source already
                                    # narrower than 1920 isn't upscaled.
                                    #
                                    # flags=lanczos: ffmpeg's default scaler
                                    # is soft on top of an already-lossy
                                    # source, and unsharp claws a bit of that
                                    # back - a frozen compressed frame reads
                                    # blurrier than the same footage in
                                    # motion even at matched resolution
                                    # (motion masks the quantization/deblock
                                    # softness codecs lean on; playback via
                                    # VideoOutput never shows a truly static
                                    # frame the way this thumbnail does), so
                                    # this only narrows the gap, not closes it.
                                    [ "$needwide" = "1" ] && ffmpeg -y -v error -i "$f" -vframes 1 -vf "scale='min(1920,iw)':-1:flags=lanczos,unsharp=5:5:0.8:5:5:0.0" "$wide"
                                fi
                            elif ! command -v magick >/dev/null 2>&1; then
                                if [ "$warnedMagick" = "0" ] && [ "$alerts" = "1" ]; then
                                    warnedMagick=1
                                    notify-send -a pibble -i system-software-install "magick not found" "ImageMagick is used to generate wallpaper thumbnails and blurred previews - install it for sharper, faster previews."
                                fi
                            else
                                # "$f[0]": first frame only, so an animated
                                # .gif source still yields a static
                                # crop/blur (only the selected/centered
                                # tile/window plays the source file itself)
                                [ "$needcrop" = "1" ] && magick "$f[0]" -resize 480x270^ -gravity center -extent 480x270 "$cachedir/thumbnails/crops/$key.$oext"
                                # The wide still: the same frame
                                # uncropped, bounded to the box a video's
                                # already gets (see the ffmpeg call above), so
                                # both types feed that strip the same picture
                                # at the same quality. The trailing > only
                                # ever shrinks - a source already smaller
                                # comes through as it is rather than being
                                # upscaled into the cache.
                                #
                                # This exists purely to keep the decode off the
                                # original: a 5K PNG costs ~280ms to decode
                                # even asked for at 440px tall (unlike a JPEG,
                                # PNG has no scaled decode path - the whole
                                # thing is unpacked, then resized), and the
                                # carousel pays that again for every cell that
                                # wraps around the strip. At 1920 wide it is
                                # ~30ms. JPEG, not the true-color PNG the
                                # other variants are written as: nothing
                                # downstream re-blurs this one, so there is no
                                # banding to protect against, and a q92 file is
                                # a quarter the size. Alpha flattened onto
                                # black explicitly - the format can't carry it
                                # and magick would otherwise pick white, which
                                # is not what a transparent wallpaper composites
                                # over on the desktop.
                                [ "$needwide" = "1" ] && magick "$f[0]" -resize '1920x1080>' -background black -alpha remove -alpha off -quality 92 "$wide"
                            fi
                        fi
                        # The blurred variant: the wallpaper as the compositor
                        # would blur it behind the launcher (see the xray
                        # block on root for where the numbers come from),
                        # which is also what the wallpaper command gets as
                        # $BLUR. A video goes through the still frame ffmpeg
                        # just wrote, since magick can't read one.
                        #
                        # Cropped to the output's aspect so the launcher's
                        # PreserveAspectCrop has nothing left to crop and the
                        # blur lands at the sigma it was baked for. The crop
                        # rounds to a whole pixel of an image a quarter of the
                        # screen's size, which measures ~3 output pixels below
                        # the compositor's blur of the same wallpaper -
                        # deliberately left as is.
                        if [ "$needblur" = "1" ] && command -v magick >/dev/null 2>&1; then
                            bsrc="$f"
                            [ "$isvid" = "1" ] && bsrc="$wide"
                            [ -e "$bsrc" ] && magick "$bsrc[0]" -resize "$xgeom^" -gravity center -extent "$xgeom" -blur "0x$xsigma" -color-matrix "1.3937 -0.3576 -0.0361, -0.1063 1.1424 -0.0361, -0.1063 -0.3576 1.4639" "$cachedir/blurred/$bkey.png"
                        fi
                    done
                    # clips/ is not swept here: the clipboard owns it, keys it
                    # by entry id rather than source path, and prunes it
                    # against clipsMax on its own scan
                    for d in "$cachedir/thumbnails/crops" "$cachedir/thumbnails/wide" "$cachedir/blurred"; do
                        # with nothing asking for blurred variants the keys
                        # this pass knows are not the ones those files were
                        # baked under, so leave them alone rather than
                        # sweeping the lot: asking again picks them straight
                        # back up, and any entry that really is dead by then
                        # goes with the first sweep that can tell.
                        [ "$d" = "$cachedir/blurred" ] && [ "$gb" != "1" ] && continue
                        for c in "$d"/*; do
                            [ -e "$c" ] || continue
                            k=$(basename "$c"); k="\${k%.*}"
                            case " $live " in *" $k "*) ;; *) rm -f "$c" ;; esac
                        done
                    done`, "_", root.dir, SystemInfo.cacheRoot, wantBlur ? "1" : "0", Settings.alertEnabled("missingDeps") ? "1" : "0",
                    root.xraySize.width + "x" + root.xraySize.height, String(root.xrayCacheSigma)].concat(order));
            }
        }
    }

    // ---------- the blurred wallpaper ----------
    // The client-side blur ("xray", see Settings.bgBlur) draws the wallpaper
    // blurred into the cache alongside its thumbnail (see scan), rather
    // than blurring live every time the launcher opens. niri's own xray mode
    // works the same way, and for the same reason: the wallpaper is the only
    // thing being blurred and it almost never changes, so blurring it once
    // and reusing the result is free from then on. Live blur, by contrast,
    // pays a shader compile plus a screen-sized offscreen pass on the first
    // frame after the layer surface maps - long enough to watch the backdrop
    // turn up late behind a grow reveal. The same file is what a wallpaper
    // command gets as $BLUR (see LauncherWindow.applyWallpaper).
    //
    // The kernel is cloned from niri's defaults (`blur { passes 3; offset 3;
    // noise 0.02; saturation 1.5 }`). Its dual kawase chain - 3 downsample
    // then 3 upsample passes, each tapping at `offset` halves of a
    // destination pixel with the 5/8-tap kernels in
    // src/render_helpers/shaders/blur_{down,up}.frag - has an impulse
    // response indistinguishable from a gaussian of sigma 19.17: simulating
    // the chain and blurring a hard edge with `-blur 0x19.17` both spread it
    // over exactly 50px, 10% to 90%. So one gaussian is the whole chain.
    //
    // Saturation is niri's postprocess step: a mix toward Rec.709 luma,
    // applied to the blurred result in the same non-linear sRGB the blur
    // itself runs in (its textures are plain 8-bit ABGR, no linearization) -
    // which is what -color-matrix does here, and why nothing converts to
    // linear light first. Niri's noise step is the one part deliberately not
    // reproduced: it can't be baked in (this image is upscaled on the way to
    // the screen, so it would land as blotches rather than dither), and the
    // alternative - a noise tile drawn live over the backdrop - is a
    // full-screen texture that also shows as grain over the desktop whenever
    // there's no wallpaper baked to sit under it. The banding it would have
    // hidden is accepted instead.
    //
    // Sigma is niri's radius in *output* pixels. On a fractionally scaled
    // output the compositor hands anyone not speaking wp-fractional-scale a
    // rounded wl_output scale (niri reports 2 for a 1.25x output, which is
    // what a ShellScreen's devicePixelRatio - and a window's, until its
    // surface is mapped - comes back as), so dividing by that lands the blur
    // a long way off. A mapped surface is told the real fractional scale, so
    // that is what gets measured. See XrayScaleProbe.
    readonly property real xraySigma: 19.17
    // Baked at a quarter of the output's logical resolution. A blur this
    // wide leaves nothing that a quarter-rate sampling can't carry: against
    // the same blur done at full output resolution, the quarter-size bake
    // scaled back up measures 55dB PSNR - visually identical, at a sixteenth
    // of the magick run, the file size, the decode and the texture upload.
    readonly property int xrayScale: 4
    readonly property size xraySize: {
        const s = root.screen;
        if (!s)
            return Qt.size(0, 0);
        return Qt.size(Math.max(1, Math.round(s.width / root.xrayScale)), Math.max(1, Math.round(s.height / root.xrayScale)));
    }
    // output pixels per logical pixel, 0 until measured (see
    // XrayScaleProbe). Nothing bakes until it resolves - baking a whole
    // wallpaper folder at the wrong sigma and then again at the right one
    // is minutes of pointless work - but it always resolves, to 1 if the
    // measurement can't be made.
    property real xrayOutputScale: 0
    // Every output measured so far, by name. The launcher follows the
    // compositor's focused output (see LauncherWindow.syncScreen), so `screen`
    // changes whenever it opens on a different monitor - and a different output
    // can have a different fractional scale, which is the unit xraySigma is
    // expressed in, so the measurement has to be made again there. Remembering
    // it per output is what keeps moving *back* free: an unmeasured output
    // spends a probe (~500ms) with the backdrop dropped to the live-blur
    // fallback, since a scale of 0 is also what holds the bake back.
    property var xrayOutputScales: ({})
    onScreenChanged: root.xrayOutputScale = (root.screen ? root.xrayOutputScales[root.screen.name] : 0) ?? 0
    // the blur as it applies to the baked image rather than to the screen:
    // output pixels -> logical pixels -> the quarter-size image. 0 while the
    // scale is unknown, which is what holds the bake back.
    readonly property real xrayCacheSigma: root.xrayOutputScale > 0 ? root.xraySigma / root.xrayOutputScale / root.xrayScale : 0
    // The baked backdrop for the current wallpaper, or "" if there isn't one
    // yet (no ImageMagick, or a folder still being worked through), which
    // falls the launcher back to blurring live.
    readonly property string xrayBlur: {
        if (Settings.bgBlur !== "xray")
            return "";
        const w = root.list.find(x => x.path === Settings.currentWallpaper);
        return w ? w.blur : "";
    }
    // Everything the backdrop could draw, best first: the bake, or - until
    // there is one - the raw wallpaper for the launcher to blur live. That
    // fallback is only worth naming once a scan that was actually looking for
    // the current backdrops has come back without one (see scanKey); before
    // that it is just a full-size wallpaper decode that the bake replaces
    // moments later.
    readonly property string xrayWant: {
        if (Settings.bgBlur !== "xray")
            return "";
        if (root.xrayBlur !== "")
            return root.xrayBlur;
        return root.scanKey === root.xrayCacheKey ? root.matugenSource : "";
    }
    // What the backdrop actually draws, and whether that is the raw wallpaper
    // - i.e. whether the launcher has to blur it itself.
    property string xrayShown: ""
    property bool xrayShownLive: false
    function syncXrayShown() {
        // Only ever swapped while the launcher is down. Two things move it,
        // and neither is watchable mid-open:
        //
        //   - applying a wallpaper leaves the launcher open on the picker,
        //     where the tiles hide the backdrop, so the swap only shows as the
        //     UI fades out on the way to closing - which reads as the backdrop
        //     changing out from under the exit animation.
        //   - the output scale resolving (see XrayScaleProbe, ~1.4s after a
        //     daemon start, and later than that with Settings.preload on)
        //     re-keys every cache entry, walking xrayWant through "" and then
        //     a bake that still has to be decoded. An Image drops what it is
        //     showing the moment its source changes, so on a first open caught
        //     inside that window it is a backdrop-shaped hole under the reveal
        //     - measured 600ms of nothing at all, the decode being that slow
        //     against a first open's busy GUI thread.
        //
        // Drawing nothing is the one thing worse than swapping late, so an
        // empty backdrop takes whatever is going immediately: on a cold cache
        // the alternative is a whole first open with no backdrop at all. Same
        // for a backdrop nobody is looking at, which is what the mode being
        // off makes this.
        if (root.launcherShown && root.xrayShown !== "" && Settings.bgBlur === "xray")
            return;
        root.xrayShownLive = root.xrayWant !== "" && root.xrayBlur === "";
        root.xrayShown = root.xrayWant;
    }
    onXrayWantChanged: root.syncXrayShown()
    // Everything the baked files are named after. A new output geometry or
    // scale (or switching the mode on at all) changes every name, so the
    // scan has to run again to generate the new ones and sweep the old.
    readonly property string xrayCacheKey: (Settings.bgBlur === "xray" || Settings.wallCommand.includes("$BLUR") ? "on" : "off")
        + "|" + root.xraySize.width + "x" + root.xraySize.height + "|" + root.xrayCacheSigma
    onXrayCacheKeyChanged: root.rescan()

    // Measures the output scale that xraySigma needs, once, off the device
    // pixel ratio of a mapped surface (see XrayScaleProbe). Only ever runs in
    // "xray" mode, and the surface it needs to exist on goes away the moment
    // the number lands. A compositor that never reports one just leaves the
    // timeout below to settle it at 1, i.e. logical pixels stand in for output
    // pixels, which is exactly right on an unscaled output.
    readonly property bool xrayScaleWanted: (Settings.bgBlur === "xray" || Settings.wallCommand.includes("$BLUR"))
        && root.xrayOutputScale === 0 && root.screen !== null
    // `output` is the name of the output the measurement was taken on, which is
    // not necessarily the one in use by the time it lands: the probe settles on
    // a debounce (see XrayScaleProbe), and the launcher can move to another
    // monitor inside that window.
    function setXrayOutputScale(s, output) {
        // a bad measurement (a surface that never mapped, a screen that
        // resized mid-measure) must still resolve to something, or nothing
        // would ever bake
        const scale = s > 0.1 ? s : 1;
        // mutated in place deliberately - nothing binds to the map, it is only
        // ever read back on a screen change
        if (output)
            root.xrayOutputScales[output] = scale;
        // a measurement for an output that is no longer the one in use is worth
        // filing but not applying; the probe is already re-running against the
        // current one, and adopting this would bake the folder at its sigma
        if (!output || !root.screen || output === root.screen.name)
            root.xrayOutputScale = scale;
    }
    Timer {
        id: xrayScaleTimeout
        interval: 3000
        running: root.xrayScaleWanted
        onTriggered: root.setXrayOutputScale(1, root.screen ? root.screen.name : "")
    }
}
